# Generated by Django 5.2.7 on 2025-10-05 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Напишите название книги')),
                ('description', models.TextField(verbose_name='Напишите описание книги')),
                ('image', models.ImageField(upload_to='books/', verbose_name='Выберите изображение книги')),
                ('quantity_page', models.PositiveIntegerField(verbose_name='Количество страниц')),
                ('author', models.CharField(blank=True, max_length=100, verbose_name='Автор книги')),
                ('book_audio', models.URLField(blank=True, null=True, verbose_name='Ссылка на аудиокнигу')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'verbose_name': 'книга',
                'verbose_name_plural': 'книги',
            },
        ),
    ]
