# Generated by Django 5.2.7 on 2025-10-06 12:31

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название книги')),
                ('description', models.TextField(verbose_name='Описание книги')),
                ('image', models.ImageField(upload_to='books/', verbose_name='Изображение книги')),
                ('quantity_page', models.PositiveIntegerField(verbose_name='Количество страниц')),
                ('author', models.CharField(blank=True, max_length=100, verbose_name='Автор книги')),
                ('book_audio', models.URLField(blank=True, null=True, verbose_name='Ссылка на аудиокнигу')),
                ('book_url', models.URLField(blank=True, null=True, verbose_name='Ссылка на книгу')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'книга',
                'verbose_name_plural': 'книги',
            },
        ),
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название тура')),
            ],
            options={
                'verbose_name': 'тур',
                'verbose_name_plural': 'туры',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Рейтинг')),
                ('text', models.TextField(verbose_name='Отзыв')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='books.books', verbose_name='Книга')),
            ],
            options={
                'verbose_name': 'отзыв',
                'verbose_name_plural': 'отзывы',
            },
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150, verbose_name='ФИО участника')),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.tour', verbose_name='Тур')),
            ],
            options={
                'verbose_name': 'регистрация',
                'verbose_name_plural': 'регистрации',
                'constraints': [models.UniqueConstraint(fields=('full_name',), name='unique_participant')],
            },
        ),
    ]
