# Generated by Django 5.2 on 2025-10-11 13:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название серии')),
                ('order', models.PositiveIntegerField(default=1, verbose_name='Порядок серии')),
                ('video_url', models.URLField(blank=True, null=True, verbose_name='Ссылка на видео (YouTube или др.)')),
                ('video_file', models.FileField(blank=True, null=True, upload_to='episodes/', verbose_name='Локальный файл видео')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='episodes', to='books.books', verbose_name='Книга')),
            ],
            options={
                'verbose_name': 'серия',
                'verbose_name_plural': 'серии',
                'ordering': ['order'],
            },
        ),
    ]
