# Generated by Django 5.2.7 on 2025-10-05 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='book_url',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка на книгу'),
        ),
    ]
