# Generated by Django 5.2 on 2025-10-11 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_episode'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Registration',
        ),
        migrations.DeleteModel(
            name='Tour',
        ),
    ]
