# Generated by Django 5.2 on 2025-10-11 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_tour_registration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode',
            name='video_url',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка на видео (YouTube, Rutube и т.д.)'),
        ),
    ]
