# Generated by Django 5.2 on 2025-10-19 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_watchhistory_watchlist'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='watchlist',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='watchlist',
            name='book',
        ),
        migrations.RemoveField(
            model_name='watchlist',
            name='user',
        ),
        migrations.DeleteModel(
            name='WatchHistory',
        ),
        migrations.DeleteModel(
            name='Watchlist',
        ),
    ]
