# Generated by Django 5.2 on 2025-10-15 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='clothes',
            options={'verbose_name': 'Одежда', 'verbose_name_plural': 'Одежда'},
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название категории'),
        ),
        migrations.AlterField(
            model_name='clothes',
            name='categories',
            field=models.ManyToManyField(related_name='clothes', to='clothes.category', verbose_name='Категории'),
        ),
        migrations.AlterField(
            model_name='clothes',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='clothes',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='clothes/', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='clothes',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='clothes',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Название одежды'),
        ),
    ]
