# Generated by Django 5.2 on 2025-10-21 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CineBoard', '0004_movie_poster'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='channel',
            options={'verbose_name': 'Канал', 'verbose_name_plural': 'Каналы'},
        ),
        migrations.AlterModelOptions(
            name='cineitem',
            options={'verbose_name': 'Элемент Cine', 'verbose_name_plural': 'Элементы Cine'},
        ),
        migrations.AlterModelOptions(
            name='genre',
            options={'verbose_name': 'Жанр', 'verbose_name_plural': 'Жанры'},
        ),
        migrations.AlterModelOptions(
            name='moviecomment',
            options={'ordering': ['-created_at'], 'verbose_name': 'Комментарий к фильму', 'verbose_name_plural': 'Комментарии к фильмам'},
        ),
        migrations.AlterModelOptions(
            name='rating',
            options={'verbose_name': 'Рейтинг', 'verbose_name_plural': 'Рейтинги'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name': 'Тег', 'verbose_name_plural': 'Теги'},
        ),
    ]
